# Generated by Django 6.1.1 on 2026-09-12 14:45

import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('file', models.FileField(upload_to=storage.models.user_directory_path, verbose_name='Файл на диске')),
                ('size', models.BigIntegerField(verbose_name='Размер (в байтах)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен доступа')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
